/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20TradableVotes } from "./ERC20TradableVotes";
export * as factories from "./factories";
export { ERC20TradableVotes__factory } from "./factories/ERC20TradableVotes__factory";
